name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: teamwork
          POSTGRES_PASSWORD: teamwork
          POSTGRES_DB: teamwork_test_db
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      run: npm ci

    - name: Run Testsuite
      env:
        APP_NAME: 'Teamwork'
        JWT_KEY: '$yhnnj59kln1lnlgkl'
        JWT_DURATION: '1h'
        PORT: 5000
        PG_HOST: 'localhost'
        PG_PORT: 5432
        PG_USER: 'teamwork'
        PG_PASSWORD: 'teamwork'
        PG_DB_NAME: 'teamwork_test_db'
      run: npm run test:ci
