name: CI

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: teamwork
          POSTGRES_PASSWORD: teamwork
          POSTGRES_DB: teamwork_test_db
        ports:
          - 5432:5432

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install node dependencies
      run: npm ci

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Prepare Node Application
      run: cp .env.example .env.test

    - name: Run Testsuite
      run: |
        npm run test:dev
        npm run coverage
